# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3208ba70ad61e9e15f5fa996e139b5e5410e72fbdfbbbbbd696053fb0f9d85d20667024b0c458cdbecf33a189eca1376833c527dbc2cb354c957afe6e65365ba

test:
  secret_key_base: ad03ae2886e6d5f2696638417441f6535db9c3df5cae19c3a0dacf7ef15261220e41eade4543c66f3503d009cac6d9d6b3bb1a52e7b76f9141260cf2d944ea68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
